### ISSUE TITLE
Is my config for using ESP32 S3 Box 3 ok ?

### ISSUE THREAD

**Issue by kcofoni** [jlpouffier/esphome-config#1]
Hello JLo,

I watched your demos of using the ESP32-S3-BOX-3 voice assistant and I found it very cool. I bought this little beast and installed the recommended firmware. Unfortunately, I have to shout or come within 10cm to wake the assistant. That's not what I saw in the demo where you seemed quite distant !?

my configuration : 
```
substitutions:
  name: esp32-s3-box-3-5a92f4
  friendly_name: ESP32 S3 Box 3 5a92f4
  micro_wake_word_model: alexa
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
[...]
```

Using ESPHome add-on from HA to set it up.

Do you have any suggestion to fix this issue ? substitutions for improving mic sensitivity ? alternative firmware ? any other ?
For your information I tried th [Willow](https://github.com/toverainc/willow) solution and did not encounter this inconvenience.

Really appreciate the way you contribute to HA ! Thanks for that.
